---

services:
  app:
    image: go-web:local
    container_name: gw-app
    networks:
      - default
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
      # - zookeeper
      # - kafka

  postgresql:
    image: postgres:alpine
    container_name: gw-postgresql
    networks:
      - default
    environment:
      POSTGRES_DB: gowebdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: on-failure:3
    ports:
      - 5431:5432

  migrate:
    image: migrate/migrate
    networks:
      - default
    volumes:
      - C:\Users\alexa\OneDrive\Рабочий стол\goWEB\pkg\db\migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@postgresql:5432/gowebdb?sslmode=disable", "up"]
    links: 
      - postgresql
    depends_on:
      - postgresql

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   container_name: gw-zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - 22181:2181
  
  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: gw-kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - 29092:29092
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


networks:
  default:
    driver: bridge