---

services:
  app:
    container_name: gw-app
    build: .
    networks:
      - default
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgresql
      - redis

  postgresql:
    image: postgres:alpine
    container_name: gw-postgresql
    networks:
      - default
    environment:
      POSTGRES_DB: gowebdb
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    restart: always
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: gw-redis
    networks:
      - default
    restart: always
    ports:
      - 6379:6379

  migrate:
    image: migrate/migrate
    restart: on-failure:3
    networks:
      - default
    volumes:
      - /home/az/GolandProjects/Go-Bank/pkg/db/migrations:/migrations
    command: ["-path", "/migrations", "-database",  "postgres://postgres:postgres@postgresql:5432/gowebdb?sslmode=disable", "up"]
    links: 
      - postgresql
    depends_on:
      - postgresql

volumes:
  pgdata:

networks:
  default:
    driver: bridge