http:
  host: 0.0.0.0
  port: 8080

grpc:
  host: 127.0.0.1
  port: 50051

postgres-prod:
  host: gw-postgresql
  port: 5432
  user: postgres
  password: postgres
  db: gowebdb

postgres-dev:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: sa
  db: gowebdb

redis-dev:
  host: gw-redis
  port: 6379
  password: 1708
  db: 0

auth:
  secret-key: secret