http:
  host: 127.0.0.1
  port: 8080

postgres-prod:
  host: postgresql
  port: 5432
  user: postgres
  password: postgres
  db: gowebdb

postgres-dev:
  host: 127.0.0.1
  port: 5432
  user: postgres
  password: sa
  db: gowebdb